### ISSUE TITLE
Not compatible with Firefox Quantum

### ISSUE THREAD

**Issue by katrinleinweber** [mozillascience/citation-plugin#3]
Dear MozillaScience team,

That's [what AMO says](https://addons.mozilla.org/en-US/firefox/addon/code-as-a-research-object/). Will this extension/plugin be updated to support the latest Firefox versions?

Thanks for any info, and kind regards :-)

**Comment by nokeeo** [comment]
Hello @katrinleinweber .  That is not a product of this team's work.  Our product can be found [here](https://addons.mozilla.org/en-US/firefox/addon/software-citation-tools-plugin/).  It supports the current version of Firefox

**Comment by katrinleinweber** [comment]
Oh my, sooo embarrasing 😳 Thanks for the correction!

**Comment by katrinleinweber** [comment]
Maybe that link could be added in this repo's header ;-)

**Comment by katrinleinweber** [comment]
But this repo is the correct place to file issues regarding the `Software Citation Tools Plugin`, no?

**Comment by nokeeo** [comment]
Yes that is correct.
